apiVersion: apps/v1
kind: Deployment
metadata:
  name: microservices-app-a
spec:
  replicas: 2
  selector:
    matchLabels:
      app: microservices-app-a
  template:
    metadata:
      labels:
        app: microservices-app-a
    spec:
      containers:
      - name: microservices-app-a
        image: jianjustin/microservices-app-a:1.0.0
        ports:
        - containerPort: 50051 # gRPC Port
        - containerPort: 8080 # HTTP Port
