apiVersion: apps/v1
kind: Deployment
metadata:
  name: storage-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: storage-deployment
  template:
    metadata:
      labels:
        app: storage-deployment
    spec:
      containers:
        - name: storage-service
          image: jianjustin/storage-app:latest
          ports:
            - containerPort: 50000 # gRPC Port
          env:
            - name: DB_HOST
              value: "postgres"
            - name: DB_USER
              value: "jian"
            - name: DB_PASSWORD
              value: "123456"
            - name: DB_NAME
              value: "testdb"
            - name: DB_PORT
              value: "5432"
            - name: DB_SSLMODE
              value: "disable"
            - name: DB_TIMEZONE
              value: "Asia/Shanghai"
---

apiVersion: v1
kind: Service
metadata:
  name: storage-service
spec:
  type: ClusterIP
  selector:
    app: storage-deployment
  ports:
    - name: grpc
      port: 50000
      targetPort: 50000