apiVersion: v1
kind: Service
metadata:
  name: mul-service
spec:
  type: ClusterIP
  selector:
    app: mul-deployment
  ports:
    - name: grpc
      port: 50053
      targetPort: 50053
    - name: http
      port: 8083
      targetPort: 8083
