apiVersion: v1
kind: Pod
metadata:
  name: hello-k8s-pod
spec:
  containers:
    - name: hello-k8s-container
      image: jianjustin/containers:v5
      env:
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: hellok8s-secret
              key: DB_PASSWORD