apiVersion: v1
kind: Service
metadata:
  name: add-service
spec:
  type: ClusterIP
  selector:
    app: add-deployment
  ports:
    - name: grpc
      port: 50051
      targetPort: 50051
    - name: http
      port: 8081
      targetPort: 8081
