apiVersion: v1
kind: Pod
metadata:
  name: hello-k8s-pod
spec:
  containers:
    - name: hello-k8s-container
      image: jianjustin/containers:v4
      env:
        - name: DB_URL
          valueFrom:
            configMapKeyRef:
              name: hellok8s-config
              key: DB_URL