apiVersion: apps/v1
kind: Deployment
metadata:
  name: containers-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: containers
  template:
    metadata:
      labels:
        app: containers
    spec:
      containers:
        - image: jianjustin/containers:v3
          name: containers-container