apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: containers
  name: containers
spec:
  ports:
  - port: 30000
    protocol: TCP
    targetPort: 3000
  selector:
    app: containers
  type: LoadBalancer
status:
  loadBalancer: {}
